# Generated by Django 5.2 on 2025-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music',
            field=models.FileField(blank=True, null=True, upload_to='music/%Y/%m/%d'),
        ),
    ]
