# Generated by Django 5.2 on 2025-05-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_core', '0002_alter_music_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
