# Generated by Django 5.2 on 2025-05-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_core', '0003_friends_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='friends',
            name='friend_unique_code',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
