# Generated by Django 5.2 on 2025-05-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interaction_core', '0004_friends_friend_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='friend_unique_code',
            field=models.CharField(blank=True, default=False, max_length=1000),
        ),
    ]
